<?php
/** @var $block \DevGenii\SocialConnect\Block\Facebook\Button */
?>
<div class="devgenii-facebook-connect-button">
    <div id="fb-root"></div>
    <div class="fb-login-button"
         data-size="large"
         data-autologoutlink="true"
         data-show-faces="false"
         data-auto-logout-link="false"
         data-scope="<?php echo implode(',', $block->getScope()); ?>">
        <?php echo $block->getButtonText(); ?>
    </div>

    <script type="text/x-magento-init">
    {
        "*": {
            "DevGenii_SocialConnect/facebook/button": {
                "appId": "<?php echo $block->getAppId(); ?>",
                "state": "<?php echo $block->getState(); ?>",
                "ajaxUrl" :"<?php echo $block->getAjaxUrl(); ?>"
            }
        }
    }
    </script>
</div>