<?php
/** @var $block \DevGenii\SocialConnect\Block\Container\Login */
?>
<div class="devgenii-socialconnect-container devgenii-socialconnect-container-login">
    <?php if($block->facebookEnabled()): ?>
    <div class="devgenii-socialconnect-login-facebook">
        <h3><?php echo __('Facebook Connect') ?></h3>
        <p><?php echo __('You can login using your <strong>Facebook</strong> account.') ?></p>
        <?php echo $block->getChildHtml('devgenii_socialconnect.login.facebook.button'); ?>
    </div>
    <?php endif; ?>
</div>